language: minimal
sudo:     false

matrix:
  fast_finish: true
  allow_failures:
  - os: osx

env:
  - NIX_PY_VERSION=37
  - NIX_PY_VERSION=38

os:
  - linux
  - osx

branches:
  except:
    - /^docs\..*$/

install:
  - sudo curl -L https://nixos.org/nix/install | sh
  - . $HOME/.nix-profile/etc/profile.d/nix.sh

script:
  - nix-shell --pure --argstr py-version $NIX_PY_VERSION --command 'HYPOTHESIS_PROFILE=travis-ci ic-test-par'

# CACHING. See https://nixos.wiki/wiki/Nix_on_Travis

# cache:
#   directories:
#     $HOME/nix.store

# before_install:
#   - sudo mkdir -p /etc/nix
#   - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
#   - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null

# before_cache:
#   - mkdir -p $HOME/nix.store
#   - nix copy --to file://$HOME/nix.store -f default.nix buildInputs


before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install git-lfs; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then git lfs install;      fi

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then git lfs pull; fi
