# This workflow will install IC and run all the tests with pytest

name: Test suite

on:
  push:
  pull_request:

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        platform: [ubuntu-18.04, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v12
    - name: Get LFS files
      run: git lfs pull
    - name: Install IC
      run: nix-shell
    - name: Run tests
      run: nix-shell --run "HYPOTHESIS_PROFILE=travis-ci ic-test-par"
